version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:8u171-jdk
commands:
  configure-gpg:
    steps:
      - run:
          name: Configure GPG private key for signing project artifacts in OSS Sonatype
          command: |
            echo $SECRING_GPG_ASC_BASE64 | base64 --decode | gpg --batch --no-tty --import --yes
  restore-maven-cache:
    steps:
      - restore_cache:
          keys:
          - maven-m2-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
          - maven-m2-v1-{{ .Branch }}
          - maven-m2-v1
      - run:
          name: Retrieve all Maven plugins and dependencies
          command: |
            mvn  -s .circleci/maven-release-settings.xml -Prelease -Preporting --fail-never dependency:go-offline || true
  save-maven-cache:
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: maven-m2-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
  deploy:
    steps:
      - attach_workspace:
          at: .
      - restore-maven-cache
      - configure-gpg
      - run:
          name: Release new version to Maven Central
          command: |
            mvn -s .circleci/maven-release-settings.xml -Prelease deploy
            mvn -s .circleci/maven-release-settings.xml -Prelease nexus-staging:close -DstagingDescription="closing to release"
      - save-maven-cache
jobs:
  build-and-test:
    executor: maven-executor
    steps:
      - checkout
      - restore-maven-cache
      - configure-gpg
      - run:
          command: mvn -Prelease verify
      - save-maven-cache
      - persist_to_workspace:
          root: .
          paths:
            - .
      - store_artifacts:
          path: oss-build-support/target
          destination: artifacts/oss-build-support
      - store_artifacts:
          path: oss-parent/target
          destination: artifacts/oss-parent
      - store_artifacts:
          path: reflow-maven-skin/target
          destination: artifacts/reflow-maven-skin
  deploy-release:
    executor: maven-executor
    steps:
      - deploy
  deploy-snapshot:
    executor: maven-executor
    steps:
      - deploy
workflows:
  release:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /v[0-9]+(\.[0-9]+)*.*/
      - deploy-release:
          requires:
            - build-and-test
          filters:
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /v[0-9]+(\.[0-9]+)*.*/
  snapshot:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: nist-pages
      - deploy-snapshot:
          requires:
          - build-and-test
          filters:
            branches:
              only: master
 